version: '3'
services:
  app:
    build:
      context: .
    ports: 
      - 9070:9070 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    volumes:
      - app:/app
    links:
      - mysql # This service depends on mysql. Start that first.
      #- postgres # This service depends on postgres. Start that first.
    networks:
      - gorest
    deploy:
      replicas: 1

  # postgres:
  #   image: postgres:latest
  #   container_name: full_db
  #   environment:
  #     - POSTGRES_USER=${DB_USER}  
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - DATABASE_HOST=${DB_HOST} 
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - database_postgres:/var/lib/postgresql/data
  #   networks:
  #     - gorest

  mysql:
    # container_name: full_db
    image: mysql:5.7
    ports: 
      - 9050:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST} 
    volumes:
      - database_mysql:/var/lib/mysql/
      - ~/etc/localtime:/etc/localtime
    networks:
      - gorest

# nginx container
  nginx:
    # specifies the latest nginx image
    image: nginx:latest
    # Connects the conf file of the container to the conf file in our folder
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
    # It will start up the nginx only when all api containers have started
    depends_on:
      - app
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
      - "80"
    networks:
      - gorest

volumes:
  app:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  gorest:

